apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaConnect
metadata:
  name: ephemeral
  annotations:
 # use-connector-resources configures this KafkaConnect
 # to use KafkaConnector resources to avoid
 # needing to call the Connect REST API directly
   strimzi.io/use-connector-resources: "true"
spec:
  version: 2.4.0
  replicas: 1
  bootstrapServers: ephemeral-kafka-bootstrap:9093
  tls:
    trustedCertificates:
      - secretName: ephemeral-cluster-ca-cert
        certificate: ca.crt
  config:
    group.id: ephemeral-connect
    config.storage.topic: ephemeral-connect-configs
    status.storage.topic: ephemeral-connect-status
    offset.storage.topic: ephemeral-connect-offsets